kind: pipeline
type: docker
name: ecsdemo-nodejs

global-variables:
  environment: &default_docker_settings 
    CONTAINER_IMAGE: "gcr.io/messaging-305213/${DRONE_REPO_NAME}"
  
steps:
  - name: test1
    image: node:8.6.0
    group: testing
    commands:
      - node -v
      
  - name: test2
    image: 'golang:1.10-alpine'
    group: testing
    commands:
      - go version
      
  - name: build
    image: plugins/docker
    environment:
      <<: *default_docker_settings
    volumes:
    - name: dockersock
      path: /var/run/     
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $${CONTAINER_IMAGE}:$DRONE_COMMIT .
      #- docker tag $DOCKER_HUB_USERNAME/$PROJECT_NAME:${DRONE_COMMIT} $DOCKER_HUB_USERNAME/$PROJECT_NAME:${DRONE_COMMIT}
      
  - name: publish
    image: plugins/docker
    secrets: [ GCR_AUTH_TOKEN ]
    environment:
      <<: *default_docker_settings
    volumes:
    - name: dockersock
      path: /var/run/        
    commands:
      - echo Publish started on `date`
      - echo $${GCR_AUTH_TOKEN}
      #- echo $GCR_AUTH_TOKEN | docker login -u _json_key --password-stdin https://gcr.io      
      #- docker push $${CONTAINER_IMAGE}:$DRONE_COMMIT

volumes:
- name: dockersock
  host:
    path: /var/run/
