kind: pipeline
type: docker
name: linux-amd64

platform:
  arch: amd64
  os: linux
  
steps:
  - name: test1
    image: node:8.6.0
    group: testing
    commands:
      - yarn version
      
  - name: test2
    image: 'golang:1.10-alpine'
    group: testing
    commands:
      - go version
      
  - name: build
    image: 'golang:1.10-alpine'
    commands:
      - go build -o ./myapp
  - name: publish
    image: plugins/docker
    settings:
      repo: magalixcorp/k8scicd
      tags:
        - '${DRONE_COMMIT_SHA:0:7}'
        - latest
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
